package com.myspace.ejercicio1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class colaborador implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Rut")
	private java.lang.String rut;
	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Fecha Ingreso")
	private java.lang.String fechaingreso;
	@org.kie.api.definition.type.Label(value = "Apellido")
	private java.lang.String apellido;
	@org.kie.api.definition.type.Label(value = "Edad")
	private java.lang.String edad;

	public colaborador() {
	}

	public java.lang.String getRut() {
		return this.rut;
	}

	public void setRut(java.lang.String rut) {
		this.rut = rut;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getFechaingreso() {
		return this.fechaingreso;
	}

	public void setFechaingreso(java.lang.String fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.lang.String getEdad() {
		return this.edad;
	}

	public void setEdad(java.lang.String edad) {
		this.edad = edad;
	}

	public colaborador(java.lang.String rut, java.lang.String nombre,
			java.lang.String fechaingreso, java.lang.String apellido,
			java.lang.String edad) {
		this.rut = rut;
		this.nombre = nombre;
		this.fechaingreso = fechaingreso;
		this.apellido = apellido;
		this.edad = edad;
	}

}